export const settings = {
    idNoMotion:'no-motion',
    idMotion:'motion',
    idMenuButton:'menu',
    idVideo:'video-profile',
    idCercle:'circle',
    idSkillsButton:'skills-button',
    classTitleFade:'title-fade',
    classTransitionDelay:'transition-delay',
    classFadeOpacity: "fadeOpacity",
    classStepImg:'.step-img',
    classRadialFadeIn:'radialFadeIn',
    classLoaded:'loaded',
    classPfade:'.p-fade',
    classTitleSpan:'.title-span',
    classActive:'active',
    classHidden:'hidden',
    classSkillLogoUl:'skills-logo',
    classSkillInfoUl:'skills-info',
    classChecked:'checked',

}